name: Ghidra
on: [workflow_dispatch]
jobs:
  # Original author: Swyter (https://github.com/Swyter)
  # This is modified based on https://github.com/NationalSecurityAgency/ghidra/blob/4765d4e7c75b28d57c6b859ec51c79b16db3b1d5/.github/workflows/ghidra-buildbot.yml
  # swy: 64-bit windows build --
  build-win:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout diff
      uses: actions/checkout@v2
      with:
        path: patches

    - name: Checkout ghidra
      uses: actions/checkout@v2
      with:
        repository: NationalSecurityAgency/ghidra
        path: ghidra

    # Disabled because there's no patch now
    - name: Apply patches
      if: ${{ 1 > 2 }}
      run: |
        dir .
        dir patches
        cd ghidra
        dir
        git status
        for %%f in (..\patches\diff\*.patch) do (
          echo %%f:
          git apply --ignore-space-change --ignore-whitespace "%%f"
        )
        git status
      shell: cmd

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run fetchDependencies.gradle
      shell: cmd
      run: |
        cd ghidra
        gradle -I gradle/support/fetchDependencies.gradle init

    - name: Build Ghidra
      shell: cmd
      run: |
        cd ghidra
        gradle buildGhidra -x ip --stacktrace

    - name: Archive production artifacts
      if: ${{ 1 > 2 }}
      uses: actions/upload-artifact@v2
      with:
        name: WindowsGhidra
        path: ghidra/build/dist/

    - name: Test Ghidra
      if: ${{ 1 > 2 }}
      shell: cmd
      run: |
        cd ghidra
        gradle combinedTestReport
 
